/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './droppable';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
export class Wrapper_Droppable {
  /*private*/ _eventHandler:Function;
  context:import0.Droppable;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  subscription0:any;
  subscription1:any;
  subscription2:any;
  subscription3:any;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.Droppable(p0);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
    (this.subscription2 && this.subscription2.unsubscribe());
    (this.subscription3 && this.subscription3.unsubscribe());
  }
  check_dragOverClass(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.dragOverClass = currValue;
      this._expr_0 = currValue;
    }
  }
  check_dropScope(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.dropScope = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
    const currVal_2:any = true;
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      view.renderer.setElementProperty(el,'draggable',currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    if ((eventName == 'dragenter')) {
      const pd_sub_0:any = ((<any>this.context.dragEnter($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'dragover')) {
      const pd_sub_1:any = ((<any>this.context.dragOver($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'dragleave')) {
      const pd_sub_2:any = ((<any>this.context.dragLeave($event)) !== false);
      result = (pd_sub_2 && result);
    }
    if ((eventName == 'drop')) {
      const pd_sub_3:any = ((<any>this.context.drop($event)) !== false);
      result = (pd_sub_3 && result);
    }
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean,emit2:boolean,emit3:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.onDragEnter.subscribe(_eventHandler.bind(view,'onDragEnter'))); }
    if (emit1) { (this.subscription1 = this.context.onDragOver.subscribe(_eventHandler.bind(view,'onDragOver'))); }
    if (emit2) { (this.subscription2 = this.context.onDragLeave.subscribe(_eventHandler.bind(view,'onDragLeave'))); }
    if (emit3) { (this.subscription3 = this.context.onDrop.subscribe(_eventHandler.bind(view,'onDrop'))); }
  }
}