/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ng2-drag-drop.module';
import * as import2 from '@angular/core/src/di/injector';
class Ng2DragDropModuleInjector extends import0.NgModuleInjector<import1.Ng2DragDropModule> {
  _Ng2DragDropModule_0:import1.Ng2DragDropModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.Ng2DragDropModule {
    this._Ng2DragDropModule_0 = new import1.Ng2DragDropModule();
    return this._Ng2DragDropModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Ng2DragDropModule)) { return this._Ng2DragDropModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2DragDropModuleNgFactory:import0.NgModuleFactory<import1.Ng2DragDropModule> = new import0.NgModuleFactory(Ng2DragDropModuleInjector,import1.Ng2DragDropModule);